name: Python App

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      #Install Python dependencies and requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
           if [ -f r/requirements.txt ]; then pip install -r python3/requirements.txt; fi

      #With flake8 linting library lint the code
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      #Setup Python version
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      #Install Python dependencies and requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f python3/requirements.txt ]; then pip install -r python3/requirements.txt; fi
      
      #Run test of app using pytest
      - name: Test with pytest
        run: |
          RUN_ENV=dev 
          coverage run -m pytest RRS/test/
          coverage report
          coverage html -d cc_report/