
name: Examen iwalani

on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions: 
  contents: read

jobs:
#Reactivo 3: En el trabajo de linting, use una herramienta de linting (por ejemplo, Flake8)
# para verificar el código de Python en busca de errores de estilo y sintaxis. No se deben de encontrar problemas.
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10" 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f python3/requirements.txt ]; then pip install -r python3/requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  test:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f python3/requirements.txt ]; then pip install -r python3/requirements.txt; fi
      - name: Test with pytest
        env:
          AWS_REGION: us-east-1
        run: |
          RUN_ENV=dev
          coverage run -m pytest python3/test/
          coverage report
          coverage html -d cc_report/


