name: CDCI A01029956

on: 
  push:
    branches: [ A01029956 ] # Should be the main branch
  pull_request:
    branches: [ main ]

jobs:
# 1
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install flake8 pytest
          if [ -f SFMB/requirements.txt ]; then pip install -r SFMB/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
# 2
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r python3/requirements.txt
      - name: Test with pytest
        run: |
          RUN_ENV=dev
          coverage run -m pytest python3/tests/
          coverage report
          coverage html -d coverage_html/
# 3
  compiling_package:
    runs-on: ubuntu-latest
    needs: [linting, unit_tests]
    if: github.event_name != 'pull_request' # Only run on push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
# 4
  image_compiling:
    runs-on: ubuntu-latest
    needs: compiling_package
    if: github.event_name != 'pull_request' # Only run on push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
# 5
  image_insersion:
    runs-on: ubuntu-latest
    needs: [ image_compiling, compiling_package ]
    if: github.event_name != 'pull_request' # Only run on push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3