name: Lambda Pipeline

on:
  push:
    branches:
      - main
      - A01028653

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm install --prefix A01028653
      - name: Lint with ESLint
        run: npm run lint --prefix A01028653

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm install --prefix A01028653
      - name: Run Jest test suite
        run: npm test --prefix A01028653

  package:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"
      - name: Change directories
        run: cd A01028653
      - name: Install dependencies
        run: npm install --production --ignore-scripts --prefer-offline
      - name: Archive production files
        run: zip -r ${{ github.sha }}.zip .
      - name: Save package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}.zip
          path: ./${{ github.sha }}.zip

  dockerize:
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - name: Read artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}.zip
          path: .
      - name: Unzip production files
        id: unzip-files
        run: |
          unzip ${{ github.sha }}.zip
      - name: Change directories
        run: cd A01028653
      - name: List
        id: ls
        run: |
          ls
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private
      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: d0z3f1c0/501ecr
          IMAGE_TAG: a01028653
        with:
          context: ./A01028653
          push: false
          outputs: type=docker,dest=/tmp/${{ env.IMAGE_TAG }}.tar
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
      - name: Save image
        uses: actions/upload-artifact@v3
        env:
          IMAGE_TAG: a01028653
        with:
          name: ${{ env.IMAGE_TAG }}
          path: /tmp/${{ env.IMAGE_TAG }}.tar

  push:
    needs: [dockerize, package]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Read artifact
        uses: actions/download-artifact@v3
        env:
          IMAGE_TAG: a01028653
        with:
          name: ${{ env.IMAGE_TAG }}
          path: /tmp
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Push image to ECR
        id: push-ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: d0z3f1c0/501ecr
        run: |
          docker load --input /tmp/a01028653.tar
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:a01028653
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:a01028653 $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
