name: Python CI/CD Exam

on:
  push:
    branches: ["A01633010"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f FDSC/requirements.txt ]; then pip install -f FDSC/requirements.txt; fi


      - name: Linting
        run: pylint FDSC/app.py

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f FDSC/requirements.txt ]; then pip install -f FDSC/requirements.txt; fi

      - name: Testing
        run: pytest FDSC/test.py


